// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindTurbineMonitor.Api.Data;

#nullable disable

namespace WindTurbineMonitor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603151259_FixSQLiteCompatibility")]
    partial class FixSQLiteCompatibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WindTurbineMonitor.Api.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TurbineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TurbineId", "Timestamp");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("WindTurbineMonitor.Api.Models.CommandLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IssuedByUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurbineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssuedAt");

                    b.HasIndex("TurbineId", "IssuedAt");

                    b.ToTable("CommandLogs");
                });

            modelBuilder.Entity("WindTurbineMonitor.Api.Models.Turbine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MqttTopicPrefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Turbines");
                });

            modelBuilder.Entity("WindTurbineMonitor.Api.Models.TurbineMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("GearboxTemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<double?>("NacelleTemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<double?>("PowerOutputKw")
                        .HasColumnType("float");

                    b.Property<double?>("RotorRpm")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TurbineId")
                        .HasColumnType("int");

                    b.Property<double?>("WindDirectionDeg")
                        .HasColumnType("float");

                    b.Property<double?>("WindSpeedMs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TurbineId", "Timestamp");

                    b.ToTable("TurbineMetrics");
                });

            modelBuilder.Entity("WindTurbineMonitor.Api.Models.Alert", b =>
                {
                    b.HasOne("WindTurbineMonitor.Api.Models.Turbine", "Turbine")
                        .WithMany("Alerts")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("WindTurbineMonitor.Api.Models.CommandLog", b =>
                {
                    b.HasOne("WindTurbineMonitor.Api.Models.Turbine", "Turbine")
                        .WithMany("CommandLogs")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("WindTurbineMonitor.Api.Models.TurbineMetric", b =>
                {
                    b.HasOne("WindTurbineMonitor.Api.Models.Turbine", "Turbine")
                        .WithMany("Metrics")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("WindTurbineMonitor.Api.Models.Turbine", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("CommandLogs");

                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
